import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import mainWallpaper from "@/public/images/main-wallpaper.webp";
import Image from "next/image";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased bg-black text-white relative`}
        style={{ backgroundImage: `url("${mainWallpaper.src}")` }}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
