import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import "./globals.css";

import Wallpaper from "@/components/Wallpaper";
import Container from "@/components/aetherium/Container";
import Navbar from "@/components/Navbar";
import { SessionProvider } from "next-auth/react";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased bg-black text-white relative !overflow-y-hidden`}>
        <Wallpaper />
        <SessionProvider>
          <Navbar />
        </SessionProvider>

        <Container as="main" className="!pt-32 p-8 h-full overflow-y-auto">
          {children}
        </Container>
      </body>
    </html>
  );
}
